container:
  image: node:latest

test_task:
  node_modules_cache:
    folder: node_modules
    populate_script: npm ci
  lib_test_script: npm run ci.travis.lib
  demo_test_script: npm run ci.travis.demo
