container:
  image: node:latest

env:
  NG_CLI_ANALYTICS: false
  CHROME_BIN: chromium-browser

test_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: pnpm install
  lib_test_script: pnpm run ci.travis.lib
  demo_test_script: pnpm run ci.travis.demo
